# Generated by Django 6.1.1 on 2026-09-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_portal', models.CharField(choices=[('cppp', 'CPPP'), ('gem', 'GeM')], max_length=20)),
                ('source_tender_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('closing_date', models.DateTimeField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('raw_listing_text', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='tender_evidence/')),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('verdict_ready', 'Verdict Ready')], default='new', max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('source_portal', 'source_tender_id')},
            },
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('go', 'GO'), ('no_go', 'NO-GO'), ('fixable', 'FIXABLE')], max_length=20)),
                ('proof_lines', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='companies.company')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='tenders.tender')),
            ],
            options={
                'unique_together': {('tender', 'company')},
            },
        ),
    ]
