# Generated by Django 6.0.8 on 2026-09-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
