# Generated by Django 6.1.1 on 2026-09-13 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('datasheet', 'Datasheet'), ('certificate', 'Certificate'), ('financial', 'Financial Statement'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='vault_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company')),
            ],
        ),
    ]
